[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pxp-parser = { git = "https://github.com/pxp-lang/pxp" }
pxp-symbol = { git = "https://github.com/pxp-lang/pxp" }
wasm-bindgen = "0.2"